### ISSUE TITLE
Cannot find module 'core-js/stable'

### ISSUE THREAD

**Issue by noook** [noook/igdm-cli#10]
@realies 
```
$ igdm
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'core-js/stable'
Require stack:
- /Users/nook/.nvm/versions/node/v14.17.6/lib/node_modules/igdm/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /Users/nook/.nvm/versions/node/v14.17.6/lib/node_modules/igdm/dist/index.js:2:426
    at Object.<anonymous> (/Users/nook/.nvm/versions/node/v14.17.6/lib/node_modules/igdm/dist/index.js:2:17615)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nook/.nvm/versions/node/v14.17.6/lib/node_modules/igdm/dist/index.js'
  ]
}
```

Seems like I cannot run the script with node `v14.17.6`

**Comment by realies** [comment]
@noook presume yarn install does not fix that? I tried Node LTS and it seems to work fine.

**Comment by noook** [comment]
This bug happens when using the binary delivered by npm
Maybe core-js should be listed in dependencies

**Comment by realies** [comment]
Oh, I see. I can update the dependancies if you can confirm that's a fix or let me know how to replicate.

**Comment by noook** [comment]
`npm i -g igdm; igdm` to replicate

I'll try to fix it myself and release it as a beta to check if it still occurs

**Comment by noook** [comment]
It was that indeed, and I also had the problem with `regenerator-runtime`. [This release](https://github.com/noook/igdm-cli/releases/tag/v1.4.2) works.

**Comment by realies** [comment]
Thanks for the fix!
